# Generated by Django 3.0.6 on 2020-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20200509_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_movie',
            name='code',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
