# Generated by Django 3.0.6 on 2020-05-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_parsed_movie_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parsed_movie',
            name='code',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
    ]
