# Generated by Django 3.0.6 on 2020-05-20 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200509_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_movie',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 5, 20, 20, 50, 25, 887745)),
        ),
    ]
